#!/bin/bash

echo "TERM=${TERM}"
echo "tput colors=$(tput colors)"

echo -e "\e[0;31mhello world \e[0;38;5;001mhello world"
echo -e "\e[0;91mhello world \e[0;38;5;009mhello world"
echo -e "\e[1;31mhello world \e[1;38;5;001mhello world"
echo -e "\e[1;91mhello world \e[1;38;5;009mhello world"

echo -e "\e[0;31mhello world \e[0;38;5;160mhello world"
echo -e "\e[0;91mhello world \e[0;38;5;166mhello world"
echo -e "\e[1;31mhello world \e[1;38;5;160mhello world"
echo -e "\e[1;91mhello world \e[1;38;5;166mhello world"

tput sgr0; tput setaf 001; echo "hello world"
tput sgr0; tput setaf 009; echo "hello world"
tput bold; tput setaf 001; echo "hello world"
tput bold; tput setaf 009; echo "hello world"

tput sgr0; tput setaf 160; echo "hello world"
tput sgr0; tput setaf 166; echo "hello world"
tput bold; tput setaf 160; echo "hello world"
tput bold; tput setaf 166; echo "hello world"
