#!/bin/bash

#
#  Name:     rdodson41/dot-files/home/.bash/gpg-agent
#  Author:   Richard E. Dodson <richard.elias.dodson@gmail.com>
#  Created:  Tue Oct 20 01:27:08 UTC 2015
#  License:  GNU General Public License, Version 3, 29 June 2007
#
#  Copyright (C) 2015 Richard E. Dodson <richard.elias.dodson@gmail.com>
#  
#  This file is part of dot-files.
#  
#  dot-files is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#  
#  dot-files is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with dot-files. If not, see <http://www.gnu.org/licenses/>.
#

#  Set gpg agent information
export GPG_AGENT_INFO

#  Set gpg tty
export GPG_TTY="$(tty)"

#  List active gpg agents
gpg-agent-list() {
	ps -e "$@" | grep "[g]pg-agent"
}

#  Initialize a gpg agent if no gpg agents are active
gpg-agent() {
	if ! gpg-agent-list &> /dev/null; then
		command gpg-agent --verbose --daemon --write-env-file "$HOME/.gpg-agent-info" "$@"
		gpg-agent-info-update
	else
		>&2 echo "gpg-agent: error: One or more gpg agents are already active"
		return 1
	fi
}

#  Update gpg agent information
gpg-agent-info-update() {
	if [[ -f "$HOME/.gpg-agent-info" ]]; then
		source "$HOME/.gpg-agent-info"
	fi
}

#  Kill active gpg agents
gpg-agent-kill() {
	kill $(gpg-agent-list | cut -d " " -f 1)
}

#  Update gpg agent information
gpg-agent-info-update
